group_name: LightCNN
artifact: LightCNN

DEVICE: cuda
epochs: 100
train_batch_size: 64
test_batch_size: 64
loss: !new:torch.nn.BCELoss

model: !new:model.LightCNN
    in_channels: 1

train_dataset: !new:dataset.Dataset
    type: train

dev_dataset: !new:dataset.Dataset
    type: dev

train_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <train_dataset>
    batch_size: !ref <train_batch_size>
    num_workers: 2
    shuffle: True

dev_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <dev_dataset>
    batch_size: !ref <test_batch_size>
    num_workers: 2
