run_name:
group_name:
artifact:
notes:

DEVICE: cuda
epochs: 100
train_batch_size: 64
test_batch_size: 64

weights: !new:torch.Tensor
    data: [0.9, 0.1]

loss: !new:torch.nn.BCELoss
    weight: !ref <weights>

model: !new:model.LightCNN

train_dataset: !new:dataset.Dataset
    ds_path: "/content/ASVspoof2017_V2_train/ASVspoof2017_V2_train/"
    annot_path: "/content/protocol_V2/protocol_V2/ASVspoof2017_V2_train.trn.txt"

dev_dataset: !new:dataset.Dataset
    ds_path: "/content/ASVspoof2017_V2_dev/ASVspoof2017_V2_dev/"
    annot_path: "/content/protocol_V2/protocol_V2/ASVspoof2017_V2_dev.trl.txt"

eval_dataset: !new:dataset.Dataset
    ds_path: "/content/ASVspoof2017_V2_eval/ASVspoof2017_V2_eval/"
    annot_path: "/content/protocol_V2/protocol_V2/ASVspoof2017_V2_eval.trl.txt"

train_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <train_dataset>
    batch_size: !ref <train_batch_size>
    num_workers: 2
    shuffle: True

dev_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <dev_dataset>
    batch_size: !ref <test_batch_size>
    num_workers: 2

eval_dataloader: !new:torch.utils.data.DataLoader
    dataset: !ref <eval_dataset>
    batch_size: !ref <test_batch_size>
    num_workers: 2
